// <auto-generated />
namespace Swu.Portal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_new_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_new_account));
        
        string IMigrationMetadata.Id
        {
            get { return "201708080941569_add_new_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
